# Generated by Django 4.1.1 on 2023-07-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='Imagefile',
            field=models.FileField(upload_to='media/'),
        ),
    ]
